# Generated by Django 4.2.1 on 2023-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon raqam')),
                ('email', models.CharField(max_length=256, verbose_name='Email sissilka')),
                ('adress', models.CharField(max_length=256, verbose_name="Manzil so'z bilan")),
                ('instagramm', models.CharField(max_length=256, verbose_name='Instagram sissilka')),
                ('telegram', models.CharField(max_length=256, verbose_name='Telegram sissilka')),
                ('facebook', models.CharField(max_length=256, verbose_name='Facebook sissilka')),
                ('twitter', models.CharField(max_length=256, verbose_name='Twitter sissilka')),
                ('odnoklassniki', models.CharField(max_length=256, verbose_name='Ok.ru sissilka')),
                ('youtube', models.CharField(max_length=256, verbose_name='YOUTUBE sissilka')),
                ('locatsiya', models.CharField(max_length=256, verbose_name='Locatsiya sissilka')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ismi')),
                ('first_name', models.CharField(max_length=128, verbose_name='Familiyasi')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Otasini ismi')),
                ('specialty', models.CharField(max_length=256, verbose_name='Mutaxassisligi')),
                ('about_doctor', models.TextField(verbose_name='Shifokor haqida')),
                ('motto', models.TextField(verbose_name='Shifokor shiori')),
                ('phone', models.CharField(max_length=25, verbose_name='Shaxsiy Telefon raqam')),
                ('email', models.CharField(max_length=256, verbose_name='Shaxsiy Email sissilka')),
                ('instagramm', models.CharField(max_length=256, verbose_name='Shaxsiy Instagram sissilka')),
                ('telegram', models.CharField(max_length=256, verbose_name='Shaxsiy Telegram sissilka')),
                ('facebook', models.CharField(max_length=256, verbose_name='Shaxsiy Facebook sissilka')),
                ('twitter', models.CharField(max_length=256, verbose_name='Shaxsiy Twitter sissilka')),
                ('odnoklassniki', models.CharField(max_length=256, verbose_name='Shaxsiy Ok.ru sissilka')),
            ],
        ),
    ]
