# Generated by Django 4.2.1 on 2023-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contacts_adress_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name="Shifokor sur'ati"),
            preserve_default=False,
        ),
    ]
