# Generated by Django 4.2.1 on 2023-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='motto',
            field=models.TextField(default=1, verbose_name='Shifokor shiori'),
            preserve_default=False,
        ),
    ]
