# Generated by Django 4.2.1 on 2023-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_clinica',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='desc',
            new_name='desc_en',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='short_desc',
            new_name='short_desc_en',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='about_doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='motto',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='contact',
            name='adress_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan ingliz tilida"),
        ),
        migrations.AddField(
            model_name='contact',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan rus tilida"),
        ),
        migrations.AddField(
            model_name='contact',
            name='adress_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Manzil so'z bilan o'zbek tilida"),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_mobile',
            field=models.CharField(default=1, max_length=25, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_doctor_en',
            field=models.TextField(blank=True, null=True, verbose_name='Shifokor haqida ingliz tilida'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_doctor_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Shifokor haqida rus tilida'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_doctor_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Shifokor haqida o'zbek tilida"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_en',
            field=models.CharField(default=1, max_length=128, verbose_name='Familiyasi ingliz tildia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(default=1, max_length=128, verbose_name='Familiyasi rus tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_uz',
            field=models.CharField(default=1, max_length=128, verbose_name="Familiyasi o'zbek tilida"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_en',
            field=models.CharField(default=1, max_length=128, verbose_name='Otasini ismi ingliz tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_ru',
            field=models.CharField(default=1, max_length=128, verbose_name='Otasini ismi rus tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='middle_name_uz',
            field=models.CharField(default=1, max_length=128, verbose_name="Otasini ismi o'zbek tilida"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='motto_en',
            field=models.TextField(default=1, verbose_name='Shifokor shiori ingliz tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='motto_ru',
            field=models.TextField(default=1, verbose_name='Shifokor shiori rus tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='motto_uz',
            field=models.TextField(default=1, verbose_name="Shifokor shiori o'zbek tilida"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(default=1, max_length=128, verbose_name='Ismi ingliz tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_ru',
            field=models.CharField(default=1, max_length=128, verbose_name='Ismi rus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_uz',
            field=models.CharField(default=1, max_length=128, verbose_name="Ismi o'zbek tilida"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(default=1, max_length=256, verbose_name='Mutaxassisligi ingliz tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(default=1, max_length=256, verbose_name='Mutaxassisligi rus tilida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_uz',
            field=models.CharField(default=1, max_length=256, verbose_name="Mutaxassisligi o'zbek tilida"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='desc_ru',
            field=models.TextField(default=1, verbose_name="Yangilikning To'liq ma'lumoti"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='desc_uz',
            field=models.TextField(default=1, verbose_name="Yangilikning To'liq ma'lumoti"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='short_desc_ru',
            field=models.TextField(default=1, verbose_name="Yangilikning Qisqa ma'lumoti"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='short_desc_uz',
            field=models.TextField(default=1, verbose_name="Yangilikning Qisqa ma'lumoti"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(default=1, max_length=512, verbose_name='Yangilikning Sarlavha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='title_uz',
            field=models.CharField(default=1, max_length=512, verbose_name='Yangilikning Sarlavha'),
            preserve_default=False,
        ),
    ]
