# Generated by Django 4.2.1 on 2023-06-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_phone_contact_phone_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='motto_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='motto_ru',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='motto_uz',
        ),
    ]
