# Generated by Django 4.1.7 on 2023-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_contact_phone_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='desc_en',
            field=models.TextField(verbose_name="Yangilikning To'liq ma'lumoti ingliz tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='desc_ru',
            field=models.TextField(verbose_name="Yangilikning To'liq ma'lumoti rus tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='desc_uz',
            field=models.TextField(verbose_name="Yangilikning To'liq ma'lumoti o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='short_desc_en',
            field=models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti ingliz tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='short_desc_ru',
            field=models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti rus tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='short_desc_uz',
            field=models.TextField(verbose_name="Yangilikning Qisqa ma'lumoti o'zbek tilida"),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_en',
            field=models.CharField(max_length=512, verbose_name='Yangilikning Sarlavha ingliz tilida'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=512, verbose_name='Yangilikning Sarlavhai rus tilida'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=512, verbose_name="Yangilikning Sarlavhasi o'zbek tilida"),
        ),
    ]
