# Generated by Django 4.1.7 on 2023-06-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Bemorning Ismi')),
                ('first_name', models.CharField(max_length=128, verbose_name='Bemorning Familiyasi')),
                ('father_name', models.CharField(max_length=128, verbose_name='Otasining ismi')),
                ('age', models.CharField(max_length=10, verbose_name="Bemorning tug'ilgan yili")),
                ('phone', models.CharField(max_length=16, verbose_name='Bemorning telefon raqami')),
                ('data', models.DateTimeField(auto_now=True)),
                ('diagnoz', models.TextField(verbose_name='Tashxis')),
                ('recommendation', models.TextField(verbose_name='Tavsiya')),
                ('comment', models.TextField(verbose_name='Izox')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Retsep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Didscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=256)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
            ],
        ),
    ]
