# Generated by Django 4.1.7 on 2023-06-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izox'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Bemorning telefon raqami'),
        ),
    ]
