# Generated by Django 4.1.7 on 2023-06-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_patient_comment_alter_patient_father_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='data',
            new_name='date',
        ),
    ]
