# Generated by Django 4.1.7 on 2023-06-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_data_patient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
