# Generated by Django 4.1.7 on 2023-06-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_patient_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoz', models.TextField(verbose_name='Tashxis')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnoz',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recommendation',
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(verbose_name='Tavsiya')),
                ('diagnoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.diagnoz')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
    ]
