# Generated by Django 4.1.7 on 2023-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_diagnoz_remove_patient_diagnoz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='document_patient'),
        ),
    ]
