# Generated by Django 4.1.7 on 2023-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_patient_age_alter_patient_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='comment',
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='comment',
            field=models.TextField(default=1, verbose_name='Izox'),
            preserve_default=False,
        ),
    ]
