# Generated by Django 4.1.7 on 2023-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_patient_comment_diagnoz_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(default=1, verbose_name='Izox'),
            preserve_default=False,
        ),
    ]
