# Generated by Django 4.1.7 on 2023-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_patient_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoz',
            name='recommendation',
            field=models.TextField(default=1, verbose_name='Tavsiya'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
