# Generated by Django 4.1.7 on 2023-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_patient_date_diagnoz_date_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoz',
            name='image_one',
            field=models.ImageField(default=1, upload_to='', verbose_name='Birinchi rasm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='image_two',
            field=models.ImageField(default=1, upload_to='', verbose_name='Ikkinchi rasm'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
