# Generated by Django 4.1.7 on 2023-06-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_diagnoz_image_one_diagnoz_image_two_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retsep',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
